
project_id = "fbepoxpmkoejgimjiswp"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZXBveHBta29lamdpbWppc3dwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDQyNjM4MCwiZXhwIjoyMDYwMDAyMzgwfQ.BXJxwPi77Vre4e0DwJmuxNX-YsJh9Rvp1zlqP39QFOY"
