
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sucylpawaywatvclfsuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y3lscGF3YXl3YXR2Y2xmc3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTU0MDIsImV4cCI6MjA1OTI5MTQwMn0.808crWN2O5Pvc_uYFlm8ddvDOQV8XrViPZVI43Yv9fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Function to get a service role client (for admin operations)
// Note: In production, this should be an edge function or backend service
export const getAdminClient = () => {
  // In a real app, you would use service_role key in a secure backend
  // For this demo, we're using the same client
  // This is just a placeholder - in production NEVER expose admin operations in frontend code
  return supabase;
};
